---
title: "PDX and cell line digestion method DE"
author: "Kieran R Campbell"
output:
  html_document: 
    toc: true
    toc_float: true
  html_notebook: default
params:
  pseudobulk: FALSE
  cellranger_version: v3
  output_rds: output.rds
---

This document performs differential expression for the following config:

```{r}
pseudobulk <- as.logical(params$pseudobulk)
print(params)
```



```{r setup}
knitr::opts_chunk$set(echo = TRUE,
                      cache = FALSE)

suppressPackageStartupMessages({
  library(scater)
  library(SingleCellExperiment)
  library(tidyverse)
  library(glue)
  library(edgeR)
  library(limma)
  library(ggrepel)
  library(org.Hs.eg.db)
  library(fgsea)
  library(here)
  library(scran)
})

filter <- dplyr::filter
mutate <- dplyr::mutate
arrange <- dplyr::arrange

source(here("scripts/utils.R"))
```

```{r}
entrezgene_ensembl_map <- as.list(org.Hs.egENSEMBL)

map_ids <- function(entrezgenes) {
  x <- unlist(entrezgene_ensembl_map[entrezgenes])
  names(x) <- NULL
  x
}

get_summed_counts <- function(sce) {
  rowSums(as.matrix(counts(sce)))
}
```



Read in data

```{r}
all_sce_files <- dir(here(glue("data/scesets/{params$cellranger_version}/")),
                     pattern = "qc", full.names = TRUE)

sces <- lapply(all_sce_files, readRDS)
```

Now we want to remove any fresh patient samples

```{r}
sces <- lapply(sces, function(sce) {
  if(sce$sample_type[1] == "patient") {
    return(NULL)
  }
  if(!(sce$digestion_temperature[1] %in% c(6, 37))) {
    return(NULL)
  }
  if(sce$temp_de_comparison[1] == -1) { # Don't want this comparison in
    return(NULL)
  }
  if(!(sce$enzyme_mix[1] %in% c("collagenase", "cold_protease"))) {
    return(NULL)
  }
  if(sce$batch_id[1] == "20190801") {
    return(NULL) # These are the revision datasets, so don't want to do DE
  }
  
  sce
})

sces[sapply(sces, is.null)] <- NULL
```


Collapse counts to temperature and patient specific


```{r}

sce <- NULL

if(pseudobulk) {
  stop("Pseudobulk no longer supported")
  count_mat <- sapply(sces, get_summed_counts)
  
  ids <- sapply(sces, function(sce) sce$sample_id[1])
  digestion_temperatures <- sapply(sces, function(sce) sce$digestion_temperature[1])
} else {
  sces <- lapply(sces, function(sce) {
    rowData(sce)[,-c(1:2)] <- NULL
    reducedDims(sce) <- list()
    sce
  })
  
  sce <- do.call("cbind", sces)
  
  
}
```


```{r}
sce <- remove_mouse_cells(sce)
```

```{r}

ids <- sce$sample_id
digestion_temperatures <- sce$digestion_temperature
```


```{r}
print(sce)
```

```{r}
table(sce$digestion_temperature)
```




# Differential expression - edgeR-QTL

```{r}
# count_mat_filtered <- count_mat[rowSums(count_mat) > 10, ]
# 
# dge <- DGEList(count_mat_filtered) # , group = factor(ids))
# dge <- calcNormFactors(dge)
# 
# cdr <- scale(colMeans(count_mat_filtered > 0))[,1]

sce_de <- sce[rowSums(as.matrix(counts(sce))) > 10, ]

dge <- convertTo(sce_de, type = 'edgeR')

design <- model.matrix(~ ids + factor(digestion_temperatures == 37))
  
dge <- estimateDisp(dge, design = design)
fit <- glmQLFit(dge, design = design)
qlf <- glmQLFTest(fit)
tt <- topTags(qlf, n = Inf)
```

```{r}
tt <- as.data.frame(tt) %>% 
  rownames_to_column("ensembl_gene_id") %>% 
  as_tibble()
```



```{r}
tt <- mutate(tt, gene_symbol = mapIds(org.Hs.eg.db,
                               keys=tt$ensembl_gene_id,
                               column="SYMBOL",
                               keytype="ENSEMBL",
                               multiVals="first")
)
```



```{r}
tt_annot <- top_n(tt, 30, (abs(logFC)))
```

```{r}
ggplot(tt, aes(x = logFC, y = -log10(FDR))) +
  geom_point() +
  geom_text_repel(data = tt_annot, aes(label = gene_symbol))
```



```{r}
tt$cellranger_version <- params$cellranger_version
tt$pseudobulk <- pseudobulk
```



# Camera gene set enrichment analysis


```{r}
load(here("data/genesets/human_H_v5p2.rdata"))
go_gs <- Hs.H

entrezgene_ensembl_map <- as.list(org.Hs.egENSEMBL)

map_ids <- function(entrezgenes) {
  x <- unlist(entrezgene_ensembl_map[entrezgenes])
  names(x) <- NULL
  x
}
```

```{r}
go_gs_ensembl <- lapply(go_gs, map_ids)
names(go_gs_ensembl) <- sub("GO_", "", names(go_gs_ensembl))

idx <- ids2indices(go_gs_ensembl, id = rownames(fit))
cam <- camera(dge, idx, design, trend.var = TRUE)
```


```{r}
pathways <- names(go_gs_ensembl)

cam <- rownames_to_column(cam, "pathway")


df_lfc <- lapply(pathways, function(pathway) {
  tt[idx[[pathway]], ] %>% 
  summarise(mean_log2foldchange = mean(logFC), pathway = pathway)
}) %>% 
  bind_rows()

df_gs <- inner_join(cam, df_lfc) %>% 
  dplyr::mutate(significant = FDR < 0.05) %>% 
  as_tibble()

# write_csv(df_gs, params$pathway_csv)
```

```{r}
return_list <- list(
  pseudobulk = pseudobulk,
  cellranger_version = params$cellranger_version,
  edger_fit = qlf,
  design = design,
  edger_results = tt,
  camera_results = df_gs
)

saveRDS(return_list, params$output_rds)

```

