---
title: "PDX and cell line temperature figure"
author: "Kieran R Campbell"
output:
  html_document: 
    toc: true
    toc_float: true
  html_notebook: default
params:
  umap_csv: "../../figs/pdx_temp_de/umap-pdx-cl.csv"
  coregeneset_path: "../../figs/pdx_temp_de/grid_v3_pseudobulk_FALSE.rds"
  pathway_path: "../../figs/pdx_temp_de/pathway_v3_pseudobulk_FALSE.rds"
  fig_png: "../../figs/deleteme.png"
  fig_rds: "../../figs/final/pdx_cl_temp_de_fig.rds"
---

```{r}
library(tidyverse)
library(here)

source(here("scripts/utils.R"))
```

```{r}
df_umap <- read_csv(params$umap_csv)
```





```{r}
cols = c("Cold protease 6C"="#2166ac", "Collagenase 37C"="#b2182b")

temp_plot <- ggplot(df_umap, aes(x = UMAP1, y = UMAP2)) +
  geom_point(aes(colour = factor(digestion_method)), alpha = 0.5) +
  scale_colour_manual(values = cols, name = "Digestion\nmethod") +
  cowplot::theme_cowplot(font_size = 10) +
  theme_paper() +
  theme(legend.position = "right") 


plot_gene <- function(gene, cutoff = 2) {
  g <- df_umap[[gene]]
  df_umap[[gene]][g > cutoff] <- cutoff
  
  df_umap[[gene]] <- df_umap[[gene]] / cutoff
  
  ggplot(df_umap, aes(x = UMAP1, y = UMAP2)) +
    geom_point(aes_string(colour = gene), alpha = 0.3, size = 1) +
    viridis::scale_colour_viridis(name = gene) +
    cowplot::theme_cowplot(font_size = 10) +
    theme(legend.position = "right") +
    theme_paper()
}
```

```{r fig.height = 10, fig.width = 4}
umap_grid <- cowplot::plot_grid(
  temp_plot,
  plot_gene("FOS"),
  plot_gene("JUNB"),
  plot_gene("NR4A1"),
  ncol = 1,
  align = 'v'
)
```

```{r}
coregeneset <- readRDS(params$coregeneset_path)
pathway <- readRDS(params$pathway_path)
```

```{r}
coregeneset <- coregeneset + theme_paper()
pathway <- pathway + theme_paper() +
  theme(legend.position = c(0.4, 0.4),
        legend.box.background = element_rect(colour = 'black', size = .2))
```


Overall plot:

```{r}
pdx_cl_plot <- cowplot::plot_grid(
  coregeneset,
  umap_grid,
  pathway,
  nrow = 1,
  labels = "AUTO",
  rel_widths = c(1,1,1.6)
)

ggsave(params$fig_png, width = 13, height = 8)

saveRDS(last_plot(), params$fig_rds)
```


