---
title: "Primary tumour temperature DE"
author: "Kieran R Campbell"
output:
  html_document: 
    toc: true
    toc_float: true
  html_notebook: default
params:
  input_sce: input.rds
  pseudobulk: FALSE
  cellranger_version: v3
  cell_type: "Myofibroblast"
  de_csv: output.csv
  pathway_csv: output.csv
---

This document performs differential expression for the following config:

```{r}
pseudobulk <- as.logical(params$pseudobulk)
print(params)
```



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = FALSE)

suppressPackageStartupMessages({
  library(scater)
  library(SingleCellExperiment)
  library(tidyverse)
  library(glue)
  library(edgeR)
  library(limma)
  library(ggrepel)
  library(org.Hs.eg.db)
})

filter <- dplyr::filter
mutate <- dplyr::mutate
arrange <- dplyr::arrange
```

```{r}
entrezgene_ensembl_map <- as.list(org.Hs.egENSEMBL)

map_ids <- function(entrezgenes) {
  x <- unlist(entrezgene_ensembl_map[entrezgenes])
  names(x) <- NULL
  x
}

get_summed_counts <- function(sce) {
  rowSums(as.matrix(counts(sce)))
}
```

Read in data

```{r}
sce <- readRDS(params$input_sce)
```


```{r}
cell_type_to_search <- gsub("_", "/", params$cell_type) # rename stuff with slashes to stop directory naming

stopifnot(any(sce$cellassign_cluster %in% cell_type_to_search))
```


```{r}
sce <- sce[, sce$cellassign_cluster == cell_type_to_search]
```

Collapse counts to temperature and patient specific


```{r}
ids <- sort(unique(sce$id))

if(pseudobulk) {
  sces <- lapply(ids, function(id) sce[, sce$id == id])
  
  count_mat <- sapply(sces, get_summed_counts)
  
  patient_ids <- sapply(sces, function(sce) sce$patient_id[1])
  digestion_temperatures <- sapply(sces, function(sce) sce$digestion_temperature[1])
} else {
  count_mat <- as.matrix(counts(sce))
  patient_ids <- sce$patient_id
  digestion_temperatures <- sce$digestion_temperature
}
```





# Differential expression

Filter out lowly abundant genes

```{r}
count_mat_filtered <- count_mat[rowSums(count_mat) > 10, ]
```


```{r}
tryCatch({
  dge <- DGEList(count_mat_filtered)
  dge <- calcNormFactors(dge)
  
  
  design <- model.matrix(~ patient_ids + factor(digestion_temperatures == 37))
  
  v <- voom(dge, design, plot = TRUE)
  
  if(pseudobulk) {
    corfit <- duplicateCorrelation(v, design, block = factor(patient_ids))
  } else {
    corfit <- list(consensus.correlation = NA)
  }
  #   
  
  if(!is.na(corfit$consensus.correlation)) {
    fit <- lmFit(v, design, block = factor(patient_ids), correlation = corfit$consensus.correlation)
  } else {
    fit <- lmFit(v, design)
  }
  
  fit <- eBayes(fit)
  res <- decideTests(fit)
  
  # Correct the p-values and put into a data frame
  qvals <- p.adjust(fit$p.value[,ncol(fit)], method = 'BH')
},
 error = function(e) {
   f <- file(params$de_csv)
   writeLines("ensembl_gene_id,logFC,AveExpr,t,P.Value,adj.P.Val,B,gene_symbol,cell_type,cellranger_version", 
              f)
   close(f)
   
  f <- file(params$pathway_csv)
  writeLines("pathway,NGenes,Direction,PValue,FDR,mean_log2foldchange,significant,cell_type", f)
  close(f)
  knitr::knit_exit()
})

```



```{r}
tt <- topTable(fit, number = nrow(count_mat_filtered), coef = ncol(fit)) %>% 
  as.data.frame() %>% 
  rownames_to_column("ensembl_gene_id") %>% 
  as_tibble()
```

```{r}
tt <- mutate(tt, gene_symbol = mapIds(org.Hs.eg.db,
                               keys=tt$ensembl_gene_id,
                               column="SYMBOL",
                               keytype="ENSEMBL",
                               multiVals="first")
)
```



```{r}
tt_annot <- top_n(tt, 30, (abs(logFC)))
```

```{r}
ggplot(tt, aes(x = logFC, y = -log10(adj.P.Val))) +
  geom_point() +
  geom_text_repel(data = tt_annot, aes(label = gene_symbol))
```

Add in the cell type

```{r}
tt$cell_type <- params$cell_type
tt$cellranger_version <- params$cellranger_version

write_csv(tt, params$de_csv)
```


# Camera gene set enrichment analysis


```{r}
load("../../data/genesets/human_H_v5p2.rdata")
go_gs <- Hs.H

entrezgene_ensembl_map <- as.list(org.Hs.egENSEMBL)

map_ids <- function(entrezgenes) {
  x <- unlist(entrezgene_ensembl_map[entrezgenes])
  names(x) <- NULL
  x
}
```

```{r}
go_gs_ensembl <- lapply(go_gs, map_ids)
names(go_gs_ensembl) <- sub("GO_", "", names(go_gs_ensembl))

idx <- ids2indices(go_gs_ensembl, id = rownames(fit))
cam <- camera(v, idx, design, trend.var = TRUE)
```


```{r}
pathways <- names(go_gs_ensembl)

cam <- rownames_to_column(cam, "pathway")


df_lfc <- lapply(pathways, function(pathway) {
  tt[idx[[pathway]], ] %>% 
  summarise(mean_log2foldchange = mean(logFC), pathway = pathway)
}) %>% 
  bind_rows()

df_gs <- inner_join(cam, df_lfc) %>% 
  dplyr::mutate(significant = FDR < 0.05,
                cell_type = params$cell_type) %>% 
  as_tibble()

write_csv(df_gs, params$pathway_csv)
```



