---
title: "Primary tumour DE collate results"
author: "Kieran R Campbell"
output:
  html_document: 
    toc: true
    toc_float: true
  html_notebook: default
params:
  cellranger_version: v3
  pseudobulk: FALSE
  pdx_results: "../../data/pdx_temp_de/v3/DE_results_pseudobulk_FALSE.rds"
  volcano_plot: volcano.png
  grid_plot: grid.png
  pathway_plot: "figs/deleteme.png"
  output_fig: "figs/deleteme.png"
  sfig_varresp: '../../figs/deleteme.png'
  sfig_props: 'figs/deleteme.png'
  pt_umap: 'figs/all-sample-overview/primary-tumour-figs.rds'
  coregeneset_csv: '../../data/deliverables/coregene_df-FALSE-v3.csv'
  latex_core_csv: '../../latex/pt-core.csv'
  s_cor: '../../figs/deleteme.png'
  s_pct_up: '../../figs/deleteme.png'
  s_pct_up_signif: '../../figs/deleteme.png'
  stats: 'output.stats'
---


```{r}
knitr::opts_chunk$set(echo = TRUE,
                      cache = FALSE)

suppressPackageStartupMessages({
  library(tidyverse)
  library(glue)
  library(ggrepel)
  library(here)
  library(biomaRt)
  library(cowplot)
  library(xtable)
})

select <- dplyr::select

stats <- list()

source(here('scripts/utils.R'))
```


Load in data

```{r}
results_files <- dir(here(glue("data/primary_tumour_temp_de/{params$cellranger_version}")),
                 full.names = TRUE, pattern = paste0(as.character(params$pseudobulk), "*.rds"))

results <- lapply(results_files, readRDS)
```

```{r}
df <- lapply(results, `[[`, 'edger_results') %>% 
  bind_rows()
```


```{r}
coregeneset_df <- read_csv(params$coregeneset_csv)
```




# Comparison between PDX and primary tumour

```{r}
pdx_de <- readRDS(here("data/pdx_temp_de/v3/DE_results_pseudobulk_FALSE.rds"))
```


```{r}
pdx_compare_df <- inner_join(
  df,
  pdx_de$edger_results,
  by = "ensembl_gene_id",
  suffix = c("_pt", "_pdx")
)
```

```{r}
  pdx_compare_df <- mutate(pdx_compare_df,
                  cell_type = case_when(
                    cell_type == "Breast cancer cells" ~ "Breast epithelial cells",
                    cell_type == "Epithelial cells" ~ "Ovarian epithelial cells",
                    cell_type == "Monocyte_Macrophage" ~ "Monocyte/Macrophage",
                    TRUE ~ cell_type
                  ))
```


New plot (Jun 14)

Get correlations

```{r fig.width = 6, fig.height = 3}
df_cors <- group_by(pdx_compare_df, cell_type) %>% 
  summarise(logfc_cor = cor(logFC_pt, logFC_pdx, method = "spearman"))

ggplot(df_cors, aes(x = forcats::fct_reorder(cell_type, logfc_cor), y = logfc_cor))+
  geom_bar(stat = 'identity') +
  coord_flip() +
  theme_paper() +
  labs(x = "Cell type", y = "Spearman correlation, logFC cell type vs PDX epithelial")

ggsave(params$s_cor, width = 6, height = 3)
```


```{r}
top_pdx_gene <- top_n(pdx_compare_df, 40, logFC_pdx) %>% .$ensembl_gene_id
pdx_compare_df <- mutate(pdx_compare_df, is_top_pdx_gene = ensembl_gene_id %in% coregeneset_df$ensembl_gene_id)
```

```{r}
df_rplot <- group_by(pdx_compare_df, cell_type) %>% 
  #mutate(logFC_rank = rank(logFC_pt)) %>% 
  top_n(40, logFC_pt) %>% 
  ungroup()

make_plot <- function(ct) {
  df <- filter(df_rplot, cell_type == ct)
  symbol_is_na <- is.na(df$gene_symbol_pt)
  df$gene_symbol_pt[symbol_is_na] <- df$ensembl_gene_id[symbol_is_na]
  
  ggplot(df,aes(x = logFC_pt, y = forcats::fct_reorder(gene_symbol_pt, logFC_pt),
               colour = is_top_pdx_gene)) +
    geom_point() + 
    theme_paper() +
    labs(x = "logFC in primary tumour", y = "Gene", subtitle = ct) +
    theme(legend.position = "none",
          axis.text.y = element_text(size = 6)) +
    scale_colour_manual(values = c("FALSE"="black", "TRUE"="red"))
}

plotlist <- lapply(unique(df_rplot$cell_type), make_plot)

plot_grid(plotlist = plotlist)

# ggsave("../../figs/deleteme.png", width = 10, height = 10)
```

## Summarize as latex table

```{r}
df_coregene_pct <- dplyr::filter(pdx_compare_df, ensembl_gene_id %in% coregeneset_df$ensembl_gene_id) %>% 
  group_by(cell_type) %>% 
  summarise(pct_upreg = 100 * mean(logFC_pt > 0),
            pct_upreg_signif = 100 * mean(logFC_pt > 0 & FDR_pt < 0.05))
```

```{r fig.width = 6, fig.height = 4}
ggplot(df_coregene_pct, aes(y = pct_upreg, x = forcats::fct_reorder(cell_type, pct_upreg))) +
  geom_bar(stat = 'identity') +
  coord_flip() + 
  labs(y = "% genes", x = "Cell type", 
       subtitle = "% genes in PDX core digestion geneset upregulated \n in cell type in response to collagenase digestion") +
  theme_paper()

ggsave(params$s_pct_up, width = 6, height = 3)

ggplot(df_coregene_pct, aes(y = pct_upreg_signif, x = forcats::fct_reorder(cell_type, pct_upreg_signif))) +
  geom_bar(stat = 'identity') +
  coord_flip() + 
  labs(y = "% genes", x = "Cell type", 
       subtitle = "% genes in PDX core digestion geneset significantly \n upregulated in cell type in response to collagenase digestion") +
  theme_paper()

ggsave(params$s_pct_up_signif, width = 6, height = 3)
```

```{r}
df_coregene_pct_lt <- dplyr::rename(df_coregene_pct,
                                    `Cell type` = cell_type,
                                    `% upregulated` = pct_upreg,
                                    `% significantly upregulated` = pct_upreg_signif)

latex <- xtable(df_coregene_pct_lt,
                caption = "% of genes in the 37C collagenase associated digestion core gene set identified using PDX upregulated and significantly upregulated in each primary tumour cell type",
                label = NULL)



print(latex, file = params$latex_core_csv, include.rownames = FALSE)
```

```{r}
round1 <- function(x) format(round(x, 1), nsmall = 1)

stats$min_pct_upreg <- min(df_coregene_pct$pct_upreg)
stats$max_pct_upreg <- max(df_coregene_pct$pct_upreg)
stats$min_pct_upreg_signif <- min(df_coregene_pct$pct_upreg_signif)
stats$max_pct_upreg_signif <- max(df_coregene_pct$pct_upreg_signif)

stats <- lapply(stats, round1)

```



## Continue on

Define annotation data frame

```{r}
n <- 5
df_annot <- bind_rows(
  group_by(pdx_compare_df, cell_type) %>% 
    top_n(n, abs(logFC_pt)),
  group_by(pdx_compare_df, cell_type) %>% 
    top_n(n, abs(logFC_pdx))
)
```


```{r fig.width = 7, fig.height = 5}
theme_set(theme_cowplot(font_size = 11))

ggplot(pdx_compare_df, aes(x = logFC_pdx, y = logFC_pt)) +
  geom_point(aes(size = -log10(FDR_pt)), alpha = 0.3) +
  facet_wrap(~ cell_type, scales = "free") +
  geom_label_repel(data = df_annot, aes(label = gene_symbol_pt), size = 2) +
  theme(strip.background = element_rect(fill = 'grey95')) +
  labs(x = "logFC 37C vs 6C PDX",
       y = "logFC 37C vs 6C Primary tumour") +
  scale_colour_viridis_c()

ggsave(here("figs/deleteme.png"), width = 8, height = 6)
```



# Volcano plots

```{r}
df_ann <- filter(df, FDR < 0.05) %>% 
  group_by(cell_type) %>% 
  top_n(20, 1/FDR)
```


```{r}
ggplot(df, aes(x = logFC, y = -log10(FDR)))+
  geom_point() +
  facet_wrap(~ cell_type, scales = "free", nrow = 2) +
  geom_hline(yintercept = -log10(0.05), colour = 'darkred', linetype = 2) +
  cowplot::theme_cowplot(font_size = 11) +
  geom_label_repel(aes(label = gene_symbol), data = df_ann, size = 2)
```

```{r}
ggsave(params$volcano_plot, width = 15, height = 6)
```



# Core gene set

Construct core gene set


Let's take the top 40 genes

```{r}
coregenes <- top_n(coregeneset_df, 40, abs(logFC)) %>% .$ensembl_gene_id
```



```{r}
df_cg <- filter(df, ensembl_gene_id %in% coregenes) %>% 
  mutate(significant = FDR < 0.05)

df_cg <- mutate(df_cg,
                cell_type = case_when(
                  cell_type == "Epithelial cells" ~ "Ovarian epithelial",
                  cell_type == "Breast cancer cells" ~ "Breast epithelial",
                  cell_type == "Monocyte_Macrophage" ~ "Monocyte/Macrophage",
                  TRUE ~ cell_type
                ))

ggplot(df_cg, aes(y = cell_type, x = forcats::fct_reorder(gene_symbol, -logFC), size = logFC)) +
  geom_point(aes(fill = logFC, colour = significant), shape = 21) +
  scale_fill_gradient2(low = scales::muted("blue"), high = scales::muted("red"), name = "log(fold change)") +
  # cowplot::theme_cowplot(font_size = 11) +
  theme_bw() +
  theme(legend.text = element_text(colour = 'black')) +
  scale_colour_manual(values = c("TRUE"="black", "FALSE"="grey90"), guide = FALSE) +
  theme_paper() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        legend.position = "bottom") +
  scale_size(guide = FALSE) +
  labs(x = "Digestion method associated gene", y = "Cell type") 
```

```{r}
de_grid <- last_plot()
```


```{r}
ggsave(params$grid_plot, width = 9, height = 4.5)
```

# Pathway plot

```{r}
dfp <- lapply(results, `[[`, 'camera_results') %>% 
  bind_rows()
```

```{r}
dfp <- mutate(dfp,
                cell_type = case_when(
                  cell_type == "Epithelial cells" ~ "Ovarian epithelial",
                  cell_type == "Breast cancer cells" ~ "Breast epithelial",
                  cell_type == "Monocyte_Macrophage" ~ "Monocyte/Macrophage",
                  TRUE ~ cell_type
                ))
```


```{r}
dfp$pathway <- gsub("HALLMARK_", "", dfp$pathway)
dfp$pathway <- forcats::fct_reorder(dfp$pathway, -log10(dfp$FDR))
```



```{r}
retained_pathways <- group_by(dfp, pathway) %>% 
  summarise(min_fdr = min(FDR)) %>% 
  dplyr::filter(min_fdr < 0.05) %>% 
  .$pathway %>% 
  droplevels()
```



```{r, fig.height=9, fig.width=7}
filter(dfp, pathway %in% retained_pathways) %>% 
  ggplot(aes(x = cell_type, y = pathway)) +
  geom_point(aes(size = -log10(FDR), colour = Direction, alpha = significant)) +
  scale_alpha_manual(values = c("TRUE"=.8, "FALSE"=0), guide = FALSE) +
  theme_bw() +
  theme_paper() +
  theme(legend.text = element_text(colour = 'black')) +
  theme(panel.grid.major = element_line(colour = "grey90")) +
  labs(x = "Cell type", y = "Pathway") +
  scale_colour_manual(values = c("Up"=scales::muted("red"),"Down"=scales::muted("blue"))) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text.y = element_text(size = 5)) +
  scale_y_discrete(expand = c(.04, 0))
  # theme(plot.margin=unit(c(10,1,1.5,1.2),"cm"))
  
```

```{r}
pathway_plot <- last_plot()
```


```{r}
ggsave(params$pathway_plot, width = 7, height = 10)
```

Final figure:

```{r}
bottom_grid <- cowplot::plot_grid(de_grid, pathway_plot, nrow = 1, labels = c("D", "E"),
                   rel_widths = c(1.3, 1))
```


# What looks the same and what looks different

```{r, eval=F}
unique_ensembl <- unique(df$ensembl_gene_id)

ensembl <- useMart("ensembl")
ensembl <- useDataset("hsapiens_gene_ensembl", mart=ensembl)
bm <- getBM(attributes = c("ensembl_gene_id", "hgnc_symbol"),
      filters = c("ensembl_gene_id"),
      values = unique_ensembl,
      mart = ensembl) %>% 
  as_data_frame()

dfs <- inner_join(df, bm)
```

```{r fig.width = 6, fig.height = 6, eval=F}

dfs <- filter(dfs, !(cell_type %in% c("B cells", "Plasma cells", "other"))) 

dfv <- group_by(dfs, ensembl_gene_id) %>% 
  summarise(var_logFC = var(logFC))

dfs <- mutate(dfs,
                cell_type = case_when(
                  cell_type == "Breast cancer cells" ~ "Epithelial cells",
                  cell_type == "Monocyte_Macrophage" ~ "Monocyte/Macrophage",
                  TRUE ~ cell_type
                ))

top_n(dfv, 20, var_logFC) %>% 
  inner_join(dfs) %>% 
  ggplot(aes(x = cell_type, y = logFC)) +
  facet_wrap(~ hgnc_symbol, scales = "free_x") +
  geom_bar(stat = 'identity') +
  coord_flip() +
  consistent_theme() +
  labs(x = "Cell type", y = "log fold change, 37C collagenase vs 6C cold protease")
```

```{r, eval=F}
ggsave(params$sfig_varresp, width = 10, height = 8)
```


# Save figures

```{r}
umap_figs <- readRDS(here(params$pt_umap))
```

```{r}
main_plot <- plot_grid(plot_grid(NULL, NULL, nrow = 1, labels = c("A", "B")), 
           umap_figs$umap_plot + theme_paper(),
           bottom_grid,
           ncol = 1,
           labels = c("", "C", ""),
            rel_heights = c(1.5,1.8, 1.5))

ggsave(here(params$output_fig), width = 13, height = 15)
```

Save supplementary UMAP figure

```{r}
umap_figs$prop_plot +
  cowplot::theme_cowplot(font_size = 11) +
  theme_paper() +
    theme(axis.text.x = element_text(size = 7, angle=-90, hjust=0, vjust=0.5),
          strip.text = element_text(size = 9, face='bold'))

ggsave(params$sfig_props, width = 13, height = 4)
```

```{r}
df_stat <- tibble(description = names(stats),
                  statistic = unlist(stats))
write_statistics(df_stat, file = params$stats)
```

