---
title: "SingleCellExperiment QC"
author: "Kieran R Campbell"
output:
  html_document: 
    toc: true
    toc_float: true
  html_notebook: default
params:
  input_sce_path: path_to_sce.rds
  output_sce_path: path_to_sce.rds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = FALSE)

suppressPackageStartupMessages({
  library(scater)
  library(SingleCellExperiment)
})
```

Read in the data:

```{r}
sce <- readRDS(params$input_sce_path)
print(sce)
```

# QC

Pre-qc plots:

```{r}
plotPhenoData(sce, x = "total_features_by_counts", y = "pct_counts_mito")
plotPhenoData(sce, x = "total_features_by_counts", y = "total_counts")
```


Number of cells to retain:

```{r}
cells_to_keep <- sce$total_features_by_counts > sce$filter_total_features & sce$pct_counts_mito < sce$filter_pct_counts_mito
table(cells_to_keep)
```

```{r}
sce <- sce[,cells_to_keep]
print(sce)
```


# Recompute size factors

```{r}
ncells <- ncol(sce)

if(ncells > 200) {
  sce <- scran::computeSumFactors(sce)
} else {
  sce <- scran::computeSumFactors(sce, sizes = seq(round(ncells / 8), round(ncells / 4), 1))
}

```

# Reduced dimension visualization

Run PCA first:

```{r}
sce <- runPCA(sce, ncomponents = 3)
```

```{r}
set.seed(123L)
sce <- runTSNE(sce)

tryCatch({
  sce <- runUMAP(sce, n_neighbours = min(15, round(ncol(sce) / 2)))
}, error = function(e) NULL
)
  
```


PCA plots:

```{r}
plotPCA(sce, colour_by = "total_features_by_counts")
plotPCA(sce, colour_by = "pct_counts_mito")
plotPCA(sce, colour_by = "pct_counts_ribo")
```


```{r}
plotPhenoData(sce, x = "total_features_by_counts", y = "pct_counts_mito")
plotPhenoData(sce, x = "total_features_by_counts", y = "total_counts")
```

And save to file:

```{r}
saveRDS(sce, params$output_sce_path)
```





