---
title: "All sample comparison of mitochondrial tissues"
author: "Kieran R Campbell"
output:
  html_document: 
    toc: true
    toc_float: true
  html_notebook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = FALSE)

suppressPackageStartupMessages({
  library(scater)
  library(DropletUtils)
  library(SingleCellExperiment)
  library(tidyverse)
  library(ggridges)
  library(broom)
})

# Columns of rowData(sce) that need removed to merge
cols_to_remove <- c(
  "mean_counts",
  "log10_mean_counts",
  "n_cells_by_counts",
  "pct_dropout_by_counts",
  "total_counts",
  "log10_total_counts",
  "n_cells_counts",
  "pct_dropout_counts"
)

remove_cols <- function(sce) {
  rowData(sce)[cols_to_remove] <- NULL
  sce
}
```

# Read in data

Let's grab the list of all the raw scesets:

```{r}
all_raw <- dir("../../data/scesets/", pattern = "raw", full.names = TRUE)
```

Now get the pct mito from these as well as sample names


Define function:
```{r}
read_and_get_coldata <- function(path) {
  sce <- readRDS(path)
  as.data.frame(colData(sce)) %>% 
    as_tibble()
}
```

And read:

```{r}
coldata_all <- map_df(all_raw, read_and_get_coldata)
```


# Plots

Mitochondrial:

```{r}
ggplot(coldata_all, aes(x = pct_counts_mito)) +
  geom_histogram() +
  facet_wrap(~ id, scales = "free_y") +
  labs(x = "% counts mitochondrial") +
  scale_x_continuous(expand = c(0,0)) +
  theme_bw()

ggsave("../../figs/all_sample_analyses/pct_counts_mito_all_samples.png", width = 14, height = 10)
```

Doublet score across all cells:

```{r}
ggplot(coldata_all, aes(x = doublet_score)) +
  geom_histogram() +
  facet_wrap(~ id) +
  scale_y_log10()
```



## GGridges plot

```{r}
mito_ids <- group_by(coldata_all, id) %>% 
  summarise(median_counts_mito = mean(pct_counts_mito)) %>% 
  arrange((median_counts_mito)) %>% 
  .$id
```


```{r}
coldata_all$id <- factor(coldata_all$id, levels = mito_ids)
theme_set(theme_bw())

coldata_all$sample_type <- gsub("_", " ", coldata_all$sample_type)
coldata_all$sample_type <- stringr::str_to_title(coldata_all$sample_type)
coldata_all$sample_type[coldata_all$sample_type == "Pdx"] <- "PDX"

df_ridge <- select(coldata_all, id, `% mito` = pct_counts_mito, `# genes detected` = total_features_by_counts, total_counts) %>% 
  mutate(`log10(# UMI)` = log10(total_counts)) %>% 
  select(-total_counts) %>% 
  gather(measure, value, -id)

ggplot(df_ridge, aes(x = value, y = id, group = id)) +
  geom_density_ridges(scale = 4, size = 0.25, alpha = 0.7) +
  facet_grid(~ measure, scales = "free_x") +
  labs(y = "Experiment") +
  # ggsci::scale_fill_npg(name = "Sample type") +
  theme_ridges(grid = FALSE, font_size = 11, center_axis_labels = TRUE) +
  theme(axis.text.y = element_blank(),
        legend.position = "top") +
  theme(axis.title.x = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white", colour = "white"))

ridge_plot <- last_plot()

```





## Check box

```{r}
df_grid <- select(coldata_all, id, sample_type, cancer_type, digestion_temperature, tissue_state)
df_grid <- gather(df_grid, pheno, value, -id) %>% 
  distinct()

df_grid <- mutate(df_grid,
       pheno_new = case_when(
         pheno == "cancer_type" ~ "Cancer\ntype",
         pheno == "sample_type" ~ "Substrate",
         pheno == "digestion_temperature" ~ "Digestion\ntemperature",
         pheno == "tissue_state" ~ "Tissue\nstate"
       ))

df_grid$value <- stringr::str_to_title(df_grid$value)
df_grid$value <- gsub("_", "\n", df_grid$value)
df_grid$value[df_grid$value == "Pdx"] <- "PDX"
df_grid$value[df_grid$value == "Digested\nfresh" | df_grid$value == "None"] <- "Fresh"

ggplot(df_grid, aes(x = value, y = id, fill = pheno_new)) +
  geom_point(size = 4, shape = 21, colour = 'grey20') +
  facet_grid(~ pheno_new, scales = "free_x", space = "free_x") +
  scale_fill_brewer(palette = "Spectral", guide = F) +
  labs(y = "Sample") +
  theme_bw() +
  theme(axis.title = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white", colour = "white"),
        axis.text.x = element_text(angle = -90, hjust = 0, vjust = 0.5))

grid_plot <- last_plot()
```

```{r}
cowplot::plot_grid(ridge_plot, 
                   grid_plot,
                   nrow = 1, axis = 't', align = 'hv')

ggsave("../../figs/all_sample_analyses/all_sample_overview.png", width = 10, height = 8)
```

# Overall effect sizes through regression

```{r}
df_reg <- select(coldata_all, id, sample_type, cancer_type, digestion_temperature, tissue_state,
                 pct_counts_mito, total_features_by_counts, total_counts)
```

```{r}
fit_mito <- lm(pct_counts_mito ~ sample_type + cancer_type + digestion_temperature + tissue_state, data = df_reg) %>% 
  tidy() %>% 
  mutate(response = "% mito")

fit_total_features <- lm(total_features_by_counts ~ sample_type + cancer_type + digestion_temperature + tissue_state, data = df_reg) %>% 
  tidy() %>% 
  mutate(response = "Total genes detected")

fit_total_counts <- lm(total_counts ~ sample_type + cancer_type + digestion_temperature + tissue_state, data = df_reg) %>% 
  tidy() %>% 
  mutate(response = "Total UMIs")

```


```{r}
fit_mito2 <- lm(pct_counts_mito ~ sample_type + cancer_type + digestion_temperature + tissue_state + id, data = df_reg) %>% 
  tidy() %>% 
  mutate(response = "% mito")
```




```{r}
df_metrics <- bind_rows(
  fit_mito,
  fit_total_features,
  fit_total_counts
)
```

Plot effect size of temperature:

```{r}
filter(df_reg, digestion_temperature %in% c(6, 37)) %>% 
ggplot(aes(x = factor(digestion_temperature), y = pct_counts_mito)) +
  geom_violin()
```


