import pandas as pd
import os

configfile: "../../private_config.yaml"

cellranger_versions = ['v2', 'v3']

# Parse spreadsheet
design_df = pd.read_csv(config['sample_inventory_url']).dropna()

sce_ids=list(design_df['id'])

# Input/Output files
scesets_qc = expand("../../data/scesets/{cv}/{id}_sceset_{cv}_qc.rds",
                    id=sce_ids, cv=cellranger_versions)



umap_fig_rds = expand("../../figs/all_sample_analyses/umap_all_{cv}.rds",
                      cv=cellranger_versions)
umap_fig_png = expand("../../figs/all_sample_analyses/umap_all_{cv}.png",
                      cv=cellranger_versions)
overview_figs = expand("../../figs/all_sample_analyses/all_sample_overview-{cv}.png",
                       cv=cellranger_versions)

pct_mito_fig = expand("../../figs/all_sample_analyses/pct_counts_mito_all_samples-{cv}.png",
                      cv=cellranger_versions)


rule all:
    input:
        umap_fig_rds, umap_fig_png,
        overview_figs


rule umap:
    input:
        scesets_qc
    output:
        rds="../../figs/all_sample_analyses/umap_all_{cv}.rds",
        png="../../figs/all_sample_analyses/umap_all_{cv}.png"
    shell:
        "Rscript umap-all-samples.R \
        --cellranger_version {wildcards.cv} \
        --output_png {output.png} \
        --output_rds {output.rds} "

rule overview:
    input:
        scesets_qc,
        umap_fig="../../figs/all_sample_analyses/umap_all_{cv}.rds"
    output:
        figure="../../figs/all_sample_analyses/all_sample_overview-{cv}.png",
        pct_mito_fig="../../figs/all_sample_analyses/pct_counts_mito_all_samples-{cv}.png",
        report="../../reports/all_sample_analyses/all_sample_overview-{cv}.html"
    shell:
        "Rscript -e \"rmarkdown::render('metric_overview.Rmd',\
        output_file='{output.report}', \
        params=list(cellranger_version='{wildcards.cv}', \
        input_umap_rds='{input.umap_fig}', \
        output_figure='{output.figure}', \
        pct_mito_fig='{output.pct_mito_fig}'))\" "
