---
title: "Bayesian core geneset construction"
output:
  html_document:
    df_print: paged
params:
  cellranger_version: v2
  cell_type: bcell
  output_figure: output.png
  output_gmt: output.gmt
  output_csv: output.csv
---

```{r}
suppressPackageStartupMessages({
  library(rstan)
  library(tidyverse)
  library(glue)
  library(GSEABase)
})

select <- dplyr::select
filter <- dplyr::filter
arrange <- dplyr::arrange
```


```{r}
rds_path <- glue("../../data/primary_tumour_analysis/v1/de_temperature_sample/{params$cellranger_version}/{params$cell_type}")

rds_files <- dir(rds_path, full.names = TRUE)

rds_objs <- lapply(rds_files, readRDS)

de_results <- lapply(rds_objs, `[[`, 'gene')
```


```{r}
for(sample in seq_along(de_results)) {
  de_results[[sample]]$sample <- sample
}

df_de <- bind_rows(de_results)
```



```{r}
df_de <- count(df_de, ensembl_gene_id) %>% 
  dplyr::filter(n > ifelse(length(de_results) > 1, 1, 0)) %>% 
  inner_join(df_de)
```


```{r}
model <- stan_model("../temp_de/coregene2.stan")
```

```{r}
logfcs <- select(df_de, Symbol, sample, logFC) %>% 
  spread(Symbol, logFC) %>% 
  select(-sample) %>% 
  as.matrix() %>% 
  t()

ses <- select(df_de, Symbol, sample, se) %>% 
  spread(Symbol, se) %>% 
  select(-sample) %>% 
  as.matrix() %>% 
  t()

is_missing <- 1 * (is.na(logfcs) & is.na(ses))

logfcs[is.na(logfcs)] <- 10e5
ses[is.na(ses)] <- 10e5


```

```{r}
data <- list(
  G = nrow(logfcs),
  E = ncol(logfcs),
  beta_obs = logfcs,
  beta_se = ses,
  is_missing = is_missing
)
```

```{r}
set.seed(1234L)
fit <- vb(model, data, grad_samples = 3)
```




```{r}
stan_hist(fit, 'phi')
```

```{r}
s <- summary(fit)
s <- s$summary

s <- s[grepl("^eta", rownames(s)),]
```

```{r}
dfc <- as_tibble(s) %>% 
  mutate(gene = rownames(logfcs)) %>% 
  select(gene, everything())

dfc <- dplyr::rename(dfc, lower = `2.5%`, upper = `97.5%`)
```

Add in core gene set genes

```{r}
dfc <- mutate(dfc, in_heat_geneset = lower > 0 | upper < 0)
```


```{r}
dfc_s <- filter(dfc, in_heat_geneset, abs(mean) > 0.5)

dfc_s <- arrange(dfc_s, desc(mean))

gene_order <- dfc_s$gene
dfc_s$gene <- factor(dfc_s$gene, levels = rev(gene_order))

dfc$cell_type <- params$cell_type
```



```{r fig.height = 10, fig.width = 6}
ggplot(dfc_s, aes(x = mean, y = gene)) +
  geom_errorbarh(aes(xmin = lower, xmax = upper), colour = 'grey50') +
  geom_point(aes(fill = mean), shape = 21, colour = 'black') +
  theme_bw(base_size = 10) +
  scale_fill_gradient2(low = scales::muted('blue'), high = scales::muted('red'), guide = FALSE) +
  labs(x = "Combined effect size (95% credible interval)", 
       y = "Gene", 
       subtitle = "Core heat response geneset with effect size > 0.5") 
```

Save the figure:

```{r}
saveRDS(
  last_plot(),
  glue(params$output_figure)
)
```

Save core geneset results to RDS:

```{r}
heat_genes <- filter(dfc, in_heat_geneset) %>% .$gene

gs <- GeneSet(heat_genes, geneIdType = SymbolIdentifier(), setName = glue("scrnaseq-digestion-temperature-{params$cellranger_version}-{params$cell_type}"))

toGmt(gs, glue(params$output_gmt))
```

And save the full data frame

```{r}
write_csv(dfc, glue(params$output_csv))
```



