---
title: "Primary tumour temperature differential expression collation for cellranger `r params$cellranger_version`"
author: "Kieran R Campbell"
output:
  html_document: 
    toc: true
    toc_float: true
  html_notebook: default
params:
  cellranger_version: v2
---


```{r}
knitr::opts_chunk$set(echo = TRUE,
                      cache = FALSE)

suppressPackageStartupMessages({
  library(tidyverse)
  library(glue)
})

select <- dplyr::select
```

```{r}
cell_type_map <- c(
  "bcell"="B Cells",
  "cancercell"="Cancer cells",
  "endothelial"="Endothelial",
  "monocyte"="Monoctye",
  "myofibroblast"="Myofibroblasts",
  "plasmacell"="Plasma cells",
  "tcell"="T Cells",
  "vascular_smc"="Vascular smooth muscle cell"
)
```


```{r}
csv_files <- dir(glue("../../data/primary_tumour_temp_de/{params$cellranger_version}"), full.names = TRUE, pattern="csv$")

df_de <- map_df(csv_files, read_csv)
```

```{r}
df_de <- mutate(df_de, 
                is_hsp = grepl("^HSP", gene_symbol),
                is_mito = grepl("^MT-", gene_symbol))
```

Create a mapping between comparisons and descriptive names:


```{r}
mapping = c(
  "1"="SA854 (MDA-MB-231 TNBC cell line)",
  "2"="SA604X9XB2413 (TNBC PDX)",
  "3"="SA604X9XB2417 (TNBC PDX, prev. treated)",
  "4"="SA604X8XB02164 (TNBC PDX)",
  "5" ="SA604X7XB02089 (TNBC PDX)",
  "6"="SA604X6XB01979 (TNBC PDX)",
  "7"="PBC04106 (Breast patient sample)",
  "8"="VOA11267 (HGSC patient sample)",
  "9"="PBC04573 (Breast patient sample)",
  "10"="PBC04633 (Breast patient sample)",
  "11"="VOA11294C (HGSC patient sample)",
  "12"="VOA11294F (HGSC patient sample)",
  "13"="SA604X9XB2417 (TNBC PDX)",
  "14"="SA535X5XB02887 (TNBC PDX)"
)
```


```{r}


custom_cols <- c(
  "Heat shock protein gene"="darkred",
  "Mitochondrial gene"="darkblue"
)

df_de$gene_type <- NA
df_de$gene_type[grepl("^HSP", df_de$gene_symbol)] <- "Heat shock protein gene"
df_de$gene_type[grepl("^MT-", df_de$gene_symbol)] <- "Mitochondrial gene"

df_de$description <- plyr::mapvalues(df_de$comparison, from = names(mapping), to = mapping)
```

And now we're only going to look at non-patient samples

```{r}
df_de <- filter(df_de, !grepl("patient", description))
```


```{r}
gene_df <- filter(df_de, !is.na(gene_type))

df_text <- group_by(df_de, comparison) %>% 
  top_n(10, dplyr::desc(adj.P.Val))

ggplot(df_de, aes(x = logFC, y = -log10(adj.P.Val))) +
  geom_point(colour = "grey60") +
  geom_point(data = gene_df, aes(colour = gene_type)) +
  geom_text_repel(data = df_text, aes(label = gene_symbol), size = 2.7) +
  facet_wrap(~ description, scales = "free") +
  labs(x = expression(log[2]~(fold~change)~"37C vs 6C"),
       y = expression(-log[10](q-value))) +
  scale_color_manual(values=custom_cols) +
  theme_bw() +
  theme(legend.title = element_blank(), 
        legend.position = "bottom",
        strip.background = element_rect(fill = 'grey95'),
        legend.text = element_text(size = 11),
        legend.box.background = element_rect(linetype = 1, size = 1)) 

```




```{r}
ggsave(glue("../../figs/temp_de/all_sample_volcano-{params$cellranger_version}.png"), width = 12, height = 7)
```


# Conservation of response 

```{r}
filter(df_de, is_hsp | is_mito) %>% 
  mutate(gene_symbol = fct_reorder(gene_symbol, logFC, .desc = TRUE)) %>% 
  ggplot(aes(x = gene_symbol, y = logFC)) +
  geom_boxplot(aes(fill = gene_type), outlier.shape = NA, size = 0.5) +
  geom_beeswarm(shape = 21, colour = 'black', fill = 'grey90', size = 1) +
  theme_bw() +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        legend.position = c(.8,.8),
        legend.box.background = element_rect(colour = "black")) +
  scale_fill_manual(
    values = c("Heat shock protein gene"=muted("red"),
               "Mitochondrial gene"=muted("blue"))
  ) +
  labs(x = "Gene", y = "log FC with digestion temperature")
```


```{r}
saveRDS(last_plot(), glue("../../figs/temp_de/boxplot-conserved-response-{params$cellranger_version}.rds"))
```



```{r}
filter(df_de, is_hsp | is_mito) %>% 
  mutate(gene_symbol = fct_reorder(gene_symbol, logFC, .desc = TRUE)) %>% 
  ggplot(aes(x = gene_symbol, y = logFC)) +
  # geom_boxplot(aes(fill = gene_type), outlier.shape = NA, size = 0.5) +
  geom_line(aes(group = description)) + 
  geom_point(shape = 21, aes(fill = gene_type), colour = 'grey80', size = 2) +
  theme_bw() +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        legend.position = c(.8,.8),
        legend.box.background = element_rect(colour = "black")) +
  scale_fill_manual(
    values = c("Heat shock protein gene"=muted("red"),
               "Mitochondrial gene"=muted("blue"))
  ) +
  labs(x = "Gene", y = "log FC with digestion temperature")
```

Cross plot:

```{r}
df_hm <- filter(df_de, is_hsp | is_mito)

# Life is too short to do this intelligently
unique_descriptions <- unique(df_hm$description)

dfs <- lapply(unique_descriptions, function(x) {
  dplyr::select(df_hm, gene_symbol, logFC, description) %>% 
    filter(description == x) %>% 
    dplyr::select(-description)
})

names(dfs) <- unique_descriptions

combinations <- expand.grid(unique_descriptions, unique_descriptions)

df_all <- bind_rows(
  apply(combinations, 1, function(x) {
    inner_join(dfs[[ x[1] ]], dfs[[ x[2] ]], by = "gene_symbol")
  })
)


filter(df_all, logFC.x != logFC.y) %>% 
  inner_join(select(df_hm, gene_symbol, gene_type)) %>% 
  ggplot(aes(x = logFC.x, y = logFC.y)) +
  geom_point(aes(fill = gene_type), shape = 21, colour = 'lightgrey', size = 2, alpha = 0.1) +
  guides(fill = guide_legend(override.aes = list(alpha = 1))) +
  scale_fill_manual(
  values = c("Heat shock protein gene"=muted("red"),
  "Mitochondrial gene"=muted("blue"))
  ) +
  cowplot::theme_cowplot(font_size = 10) +
  theme(legend.position = c(0.05, 0.9),
        legend.title = element_blank(),
        legend.box.background = element_rect(colour = "black")) +
  labs(x = "logFC experiment 1", y = "logFC experiment 2")

ggsave(glue("../../figs/temp_de/conservation_of_response-{params$cellranger_version}.png"), width = 4, height = 4)
```

```{r}
saveRDS(last_plot(), glue("../../figs/temp_de/conserved-response-{params$cellranger_version}.rds"))
```


# Collated pathway analysis

```{r}

csv_files <- dir(glue("../../data/temp_de_pathways/{params$cellranger_version}"), full.names = TRUE, pattern="csv$")

df_pt <- map_df(csv_files, read_csv)
```



```{r}
df_pt$description <- plyr::mapvalues(df_pt$comparison, from = names(mapping), to = mapping)

# filter so we only have non-patient samples
df_pt <- filter(df_pt, !grepl("patient", description))
```


```{r}
sum_df <- group_by(df_pt, pathway) %>% 
  summarise(min_fdr = min(FDR)) %>% 
  filter(min_fdr < 0.01) %>% 
  inner_join(df_pt, by = "pathway") %>% 
  mutate(log10FDR = -log10(FDR))


ggplot(sum_df, aes(x = pathway, y = -log10(FDR))) +
  #facet_wrap(~ pathway) +
  geom_beeswarm()
```

Let's windsorise the FDR

```{r}
thresh <- 20

sum_df <- mutate(sum_df,
                 w_log10FDR = case_when(
                   log10FDR > thresh ~ thresh,
                   log10FDR <= thresh ~ log10FDR
                 ))
```

```{r}
sum_df$pathway <- gsub("HALLMARK_", "", sum_df$pathway)

ggplot(sum_df, aes(y = description, x = pathway, fill = w_log10FDR)) +
  geom_tile() +
  viridis::scale_fill_viridis(name = expression(log[10]~"(FDR)")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 6)) +
  labs(y = "Temperature comparison", x = "Pathway")
```

```{r}
saveRDS(last_plot(), glue("../../figs/temp_de/temp_pathway-{params$cellranger_version}.rds"))
```






