import os

configfile: "primary_tumour_config.yaml"


cell_types = config['cell_types']
cellranger_versions = ['v2','v3']

base_output_path = "../../data/primary_tumour_temp_de/{cv}/{cell_type}_"
base_figure_path = "../../figs/primary_tumour_temp_de/{cv}/{cell_type}_"

figs = expand(base_figure_path + "primary_tumour_temp_de.png",
              cv=cellranger_versions,
              cell_type=cell_types)
gmts = expand(base_output_path + "primary_tumour_temp_de_geneset.gmt",
              cv=cellranger_versions,
              cell_type=cell_types)
csvs = expand(base_output_path + "primary_tumour_temp_de_results.csv",
              cv=cellranger_versions,
              cell_type=cell_types)


rule all:
    input:
        figs,gmts,csvs



rule core_geneset:
    params:
        curr_dir = os.getcwd()
    output:
        figure=base_figure_path + "primary_tumour_temp_de.png",
        gmt=base_output_path + "primary_tumour_temp_de_geneset.gmt",
        csv=base_output_path + "primary_tumour_temp_de_results.csv",
        report="../../reports/primary_tumour_temp_de/{cv}_{cell_type}.html"
    shell:
        "Rscript -e \"rmarkdown::render('{params.curr_dir}/bayesian-core-geneset.Rmd', \
        output_file='{params.curr_dir}/{output.report}', \
        knit_root_dir='{params.curr_dir}', \
        params=list(cell_type='{wildcards.cell_type}', \
        cellranger_version='{wildcards.cv}', \
        output_figure='{output.figure}', \
        output_gmt='{output.gmt}', \
        output_csv='{output.csv}'))\" "

