---
title: "Identify mouse cells across samples"
author: "Kieran R Campbell"
output:
  html_document
params:
  human_mouse_dir: '../../data/human-mouse-sces/filtered_temperature_rdata_v3'
  human_mouse_prop_file: 'output.csv'
  stats: 'stats.csv'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = FALSE)

suppressPackageStartupMessages({
  library(scater)
  library(DropletUtils)
  library(SingleCellExperiment)
  library(dplyr)
  library(tidyverse)
  library(here)
  library(ggridges)
  library(yaml)
})

source(here("scripts/utils.R"))

filter <- dplyr::filter
mutate <- dplyr::mutate
```

```{r}
config <- read_yaml(here("private_config.yaml"))
sample_ids <- read_csv(config$sample_inventory_url)
```


```{r}
sces_filenames <- dir(params$human_mouse_dir)

mouse_names <- sces_filenames[grep("^mouse", sces_filenames)] 

mouse_ids <- mouse_names %>% 
  gsub("mouse_", "", .) %>% 
  gsub(".rdata", "", ., fixed = TRUE)

human_names <- sces_filenames[grep("^human", sces_filenames)] 

human_ids <- human_names %>% 
  gsub("human_", "", .) %>% 
  gsub(".rdata", "", ., fixed = TRUE)

intersect_ids <- intersect(human_ids, mouse_ids)

setdiff(intersect_ids, mouse_ids)
setdiff(intersect_ids, human_ids)
```



```{r}
sces_human <- lapply(human_names, function(x) readRDS(file.path(params$human_mouse_dir, x)))
sces_mouse <- lapply(mouse_names, function(x) readRDS(file.path(params$human_mouse_dir, x)))


names(sces_human) <- human_ids
names(sces_mouse) <- mouse_ids
```


```{r}
extract_metric <- function(id, sce_list, organism) {
  sce <- sce_list[[id]]
  sce <- calculateQCMetrics(sce)
  dplyr::select(as.data.frame(colData(sce)), Barcode, total_counts) %>% 
    dplyr::mutate(sample_id = id, human_mouse = organism) %>% 
    as_tibble()
}

common_ids <- intersect(human_ids, mouse_ids)
df_human <- lapply(common_ids, extract_metric, sces_human, "human") %>% 
  bind_rows()
df_mouse <- lapply(common_ids, extract_metric, sces_mouse, "mouse") %>% 
  bind_rows()
```


```{r}
dfs <- inner_join(df_human, df_mouse, by = c("Barcode", "sample_id"), suffix = c("_human", "_mouse"))
```


<!-- ## --- Playground -->

<!-- ```{r} -->
<!-- sce_used <- readRDS("../../data/scesets/v3/TENX021_SA854_002_sceset_v3_qc.rds") -->

<!-- sce_human <- readRDS("../../data/human-mouse-sces/filtered_temperature_rdata_v3/human_TENX021_SA854_002.rdata") -->
<!-- sce_mouse <- readRDS("../../data/human-mouse-sces/filtered_temperature_rdata_v3/mouse_TENX021_SA854_002.rdata") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- sce_human <- calculateQCMetrics(sce_human) -->
<!-- summary(sce_human$total_counts) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- cd1 <- as.data.frame(colData(sce_human)) %>% select(Barcode, total_counts) -->
<!-- cd2 <- as.data.frame(colData(sce_used)) %>% select(Barcode, total_counts) -->

<!-- cd <- inner_join(cd1, cd2, by = "Barcode")  -->
<!-- ggplot(cd, aes(x = total_counts.x, y = total_counts.y)) + geom_point() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- cd3 <- filter(dfs, grepl("854_002", sample_id)) %>%  -->
<!--   select(Barcode, total_counts_human, total_counts_mouse) -->

<!-- cd <- inner_join(cd, cd3, by = "Barcode") -->

<!-- filter(cd, total_counts_human == 0) -->
<!-- ``` -->


<!-- ## --- end playground -->



```{r}
dfs <- replace_na(dfs, list(human = 0, mouse = 0)) %>% 
  dplyr::mutate(human_mouse_ratio = total_counts_human / total_counts_mouse,
                sum = total_counts_human + total_counts_mouse, 
                diff = total_counts_human - total_counts_mouse,
                diff_to_sum = diff / sum)
```


```{r}
dfs <- dplyr::select(sample_ids,
              sample_id = id,
              sample_type) %>% 
  inner_join(dfs)
```



Let's add some annotation

```{r}
dfs <- mutate(dfs,
              sample_type = case_when(
                sample_type == "cell_line" ~ "Cell line",
                sample_type == "patient" ~ "Patient",
                TRUE ~ "PDX"
              ))
```

```{r}
dfs <- mutate(dfs,
              is_mouse = diff_to_sum < 0)
```

```{r}
dfs <- filter(dfs, !is.na(diff_to_sum)) # remove poorly mapped cells from both
```


Mapping between old and new:

```{r}
mapping <-  c(
"VOA11019"="SA1203SA",
"VOA11267"="SA1206",
"VOA12024"="SA1210",
"PBC04106"="SA1205",
"PBC04633"="SA1208",
"PBC04573"="SA1207"
  )
```

```{r}
for(m in names(mapping)) {
  dfs$sample_id_fixed <- gsub(m, mapping[m], dfs$sample_id)
}
```



```{r, fig.height = 10, fig.width = 6}
dfs_grouped <- group_by(dfs, sample_id_fixed, sample_type) %>% 
  dplyr::summarise(pct_mouse = 100 * mean(diff_to_sum < 0, na.rm=TRUE)) %>% 
  ungroup()


dfs_grouped %>% 
  ggplot(aes(x = forcats::fct_reorder(sample_id_fixed, pct_mouse), y = pct_mouse)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  labs(y = "% of cells mouse", x = "Sample") +
  theme_bw() +
  theme_paper() +
  theme(panel.grid.major = element_line(colour = "grey80")) +
  facet_grid( sample_type ~ ., scales = "free_y", space = "free_y")

ggsave(here("figs", "murine-contamination", "pct_cells_mouse.png"), width = 5, height = 8)
```

Statistics

```{r}
mouse_count <- dplyr::filter(dfs, sample_type != "PDX") %>% 
  group_by(is_mouse) %>% 
  dplyr::summarise(n_mouse = n()) %>% 
  ungroup()
```

```{r}
round1 <- function(x) format(round(x, 1), nsmall = 1)

stats <- list()

stats$n_mouse_ptcl <- dplyr::filter(mouse_count, is_mouse == TRUE) %>% .$n_mouse
stats$n_human_ptcl <- dplyr::filter(mouse_count, is_mouse == FALSE) %>% .$n_mouse
stats$pct_mouse_ptcl <- with(stats, round1(100 * (n_mouse_ptcl) / (n_mouse_ptcl + n_human_ptcl)))
```

```{r}
df_stat <- tibble(description = names(stats),
                  statistic = unlist(stats))
write_statistics(df_stat, file = params$stats)
```


```{r fig.width = 10, fig.height = 12}
ggplot(dfs, aes(x = total_counts_human, y = total_counts_mouse, colour = is_mouse)) +
         geom_point() +
  facet_wrap(~ sample_id, ncol = 4) +
  geom_abline(intercept = 0, slope = 1, colour = 'black')
```



```{r}
write_csv(dfs, params$human_mouse_prop_file)
```


