---
title: "PDX cell type HSP"
author: "Kieran R Campbell"
output:
  html_notebook:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = FALSE)

suppressPackageStartupMessages({
  library(scater)
  library(SingleCellExperiment)
  library(tidyverse)
  library(glue)
  library(edgeR)
  library(limma)
  library(ggrepel)
  library(org.Hs.eg.db)
  library(cowplot)
  library(mclust)
  library(scran)
  library(readxl)
})

get_ensembl_id <- function(symbol, sce) {
  stopifnot(symbol %in% rowData(sce)$Symbol)
  rownames(sce)[rowData(sce)$Symbol == symbol]
}

set.seed(123L)
```

Get the relevant PDXs:

```{r}
sample_inventory <- read_csv("https://docs.google.com/spreadsheets/d/18BRzw2hpRaI_nQkfh4-RO-ky3UOAoiu7xzZjbL59Kww/export?format=csv")
head(sample_inventory)
```

```{r}
pdx_ids <- filter(sample_inventory, sample_type == "PDX") %>% 
  .$id
```

```{r}
sce_files <- paste0("../../data/scesets/", pdx_ids, "_sceset_qc.rds")

sces <- lapply(sce_files, readRDS)
```

```{r}
run_and_plot_pca <- function(sce) {
  sce <- runPCA(sce, ncomponents = 3)
  
  title <- function(gene) labs(subtitle = paste0(gene, ": ", sce$id[1], " @ ", sce$digestion_temperature[1], "C"))
  thm <- theme(legend.position = "bottom")
  plotPCA(sce, colour_by = get_ensembl_id("B2M", sce), ncomponents = 3)
  hsp_plot <- plotPCA(sce, colour_by = get_ensembl_id("HSP90AA1", sce), ncomponents = 3) + title("HSP90AA1") + thm
  fos_plot <- plotPCA(sce, colour_by = get_ensembl_id("FOS", sce), ncomponents = 3) + title("FOS") + thm
  b2m_plot <- plotPCA(sce, colour_by = get_ensembl_id("B2M", sce), ncomponents = 3) + title("B2M") + thm
  
  cowplot::plot_grid(hsp_plot, fos_plot, b2m_plot, nrow = 1)
}

# run_and_plot_pca(sce)

pdf("../../figs/test.pdf", width = 12, height = 8)
for(sce in sces) {
  print(run_and_plot_pca(sce))
}
dev.off()
```

```{r}
library(SC3)
rowData(sce)$feature_symbol <- rowData(sce)$Symbol
counts(sce) <- as.matrix(counts(sce))
logcounts(sce) <- as.matrix(logcounts(sce))
sce <- sc3(sce, ks = 2)
plotPCA(sce, colour_by = "sc3_2_clusters")
```









