---
title: "Cell-specific temperature DE"
author: "Allen W Zhang"
output:
  html_document: 
    toc: true
    toc_float: true
  html_notebook: default
params:
  comparison: 1
  design_file: design.csv
  marker_mat: rho.csv
  output_rds: output.rds
---

This document performs differential expression for comparson `r params$comparison` for temperatures 6 and 37 only


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = FALSE)

suppressPackageStartupMessages({
  library(scater)
  library(SingleCellExperiment)
  library(tidyverse)
  library(data.table)
  library(glue)
  library(edgeR)
  library(limma)
  library(ggrepel)
  library(cellassign)
  library(cellassign.utils)
  library(scrna.sceutils)
  library(scrna.utils)
})
```

```{r}
design <- read_csv(params$design_file)
```

Get the necessary samples:

```{r}
ids <- filter(design, comparison == params$comparison) %>% 
  .$id
```

Format the SCEPaths:

```{r}
sce_paths <- sapply(ids, function(id) glue("../../data/scesets/{id}_sceset_qc.rds"))
```

Read the SCEs:

```{r}
sces <- lapply(sce_paths, readRDS)
```

We need to ditch some QC paths:

```{r}
rowdata_to_remove <- names(rowData(sces[[1]]))[13:20]
print(rowdata_to_remove)
```

```{r}
sces <- lapply(sces, function(sce) {
  rowData(sce)[rowdata_to_remove] <- NULL
  sce
})
```

And bind these:

```{r}
sce <- do.call(cbind, sces)
```

And keep only things with temperature 6 or 37:

```{r}
sce <- sce[, sce$digestion_temperature %in% c("6", "37")]
```

## CellAssign

```{r}
rho <- read.table(marker_mat, row.names = 1, header = TRUE, sep = "\t", stringsAsFactors = FALSE)
rho <- as.matrix(rho)

sce <- scran::computeSumFactors(sce)

rowdat <- rowData(sce)
gene_ids <- df_as_map(rowdat, rownames(rho), from = "symbol", to = "id")
gene_symbols <- rownames(rho)[!is.na(gene_ids)]
gene_ids <- gene_ids[!is.na(gene_ids)]

# TODO: Test this. 
Y <- as.matrix(counts(sce)[gene_ids, ]) %>% t
colnames(Y) <- gene_symbols

size_factors <- sizeFactors(sce)

# TODO: Do a grouped analysis with batch as a covariate
X <- model.matrix(~ digestion_temperature, colData(sce))

res <- cellassign(rho = rho, exprs_obj = Y, s = size_factors, X = X, data_type = "RNAseq", n_batches = 1,
                  phi_type = "cluster_specific", verbose = FALSE, num_runs = 10)

sce$cellassign_cluster <- factor(as.numeric(str_extract(res$cell_type, "[0-9]+")))
sce$cluster <- sce$cellassign_cluster
```

## DE

```{r}
celltypes <- with(colData(sce), table(dataset, cellassign_cluster))
shared_celltypes <- colnames(celltypes)[which(colMins(celltypes) > 0)]
```

```{r, results = 'hide'}
de_tables <- lapply(shared_celltypes, function(x) {
  sce_subset <- sce %>% scater::filter(cellassign_cluster == x)
  sce_subset <- scran::computeSumFactors(sce_subset)
  sce_subset <- normalize(sce_subset)
  
  sce_subset_filtered <- sce_subset[which(with(rowData(sce_subset), pct_dropout_counts < 90 & log10_total_counts > 1)),]
  sce_subset_filtered <- sce_subset_filtered %>% scater::mutate(cluster=digestion_temperature)
  
  de_table <- clusters_de(sce_subset_filtered, method = "voom", comparison = "average")
  gene_id_mapping <- rowData(sce_subset_filtered) %>% subset(select = c("id", "symbol")) %>% plyr::rename(c("id"="gene_id")) %>% unique
  
  de_table <- de_table %>% plyr::join(gene_id_mapping %>% as.data.frame)
  return(de_table)
})
names(de_tables) <- shared_celltypes
```

```{r}
ignore <- lapply(shared_celltypes, function(x) {
  p <- plot_volcano(subset(de_tables[[x]], contrast == "37"), top_n = 40, log_q_val_threshold = NULL, nrow = 1, subtitle = x)
  return(p)
})
names(ignore) <- shared_celltypes
```

```{r, results = 'asis'}
for (x in ignore) {
  print(x)
  cat("\n----\n")
}
```




