---
title: "All sample comparison of tissues for Cellranger version `r params$cellranger_version`"
author: "Kieran R Campbell"
output:
  html_document: 
    toc: true
    toc_float: true
  html_notebook: default
params:
  cellranger_version: v2
  input_umap_rds: input.rds
  output_figure: output.png
  pct_mito_fig: mito_fig.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = FALSE)

suppressPackageStartupMessages({
  library(scater)
  library(DropletUtils)
  library(SingleCellExperiment)
  library(tidyverse)
  library(ggridges)
  library(broom)
  library(glue)
  library(here)
})

# Columns of rowData(sce) that need removed to merge
cols_to_remove <- c(
  "mean_counts",
  "log10_mean_counts",
  "n_cells_by_counts",
  "pct_dropout_by_counts",
  "total_counts",
  "log10_total_counts",
  "n_cells_counts",
  "pct_dropout_counts"
)

remove_cols <- function(sce) {
  rowData(sce)[cols_to_remove] <- NULL
  sce
}

source(here("scripts/utils.R"))
```

# Read in data

Let's grab the list of all the raw scesets:

```{r}
all_raw <- dir(glue("../../data/scesets/{params$cellranger_version}"), pattern = "raw", full.names = TRUE)
```

Now get the pct mito from these as well as sample names


Define function:
```{r}
read_and_get_coldata <- function(path) {
  sce <- readRDS(path)
  sce <- remove_mouse_cells(sce)
  as.data.frame(colData(sce)) %>% 
    as_tibble()
}
```

And read:

```{r}
coldata_all <- map_df(all_raw, read_and_get_coldata)

filter(col_data_all, enzyme_mix != "MACS_mix")
```

Total count:

```{r}
print(dim(col_data_all))
```



# Plots

Mitochondrial:

```{r, fig.width = 10, fig.height = 10}
ggplot(coldata_all, aes(x = pct_counts_mito)) +
  geom_histogram() +
  facet_wrap(~ id, scales = "free_y") +
  labs(x = "% counts mitochondrial") +
  scale_x_continuous(expand = c(0,0)) +
  theme_bw()

ggsave(params$pct_mito_fig, width = 20, height = 15)
```

Doublet score across all cells:

```{r}
ggplot(coldata_all, aes(x = doublet_score)) +
  geom_histogram() +
  facet_wrap(~ id) +
  scale_y_log10()
```



## GGridges plot

```{r}
mito_ids <- group_by(coldata_all, id) %>% 
  summarise(median_counts_mito = mean(pct_counts_mito)) %>% 
  arrange((median_counts_mito)) %>% 
  .$id
```


```{r}
coldata_all$id <- factor(coldata_all$id, levels = mito_ids)
theme_set(theme_bw())

coldata_all$sample_type <- gsub("_", " ", coldata_all$sample_type)
coldata_all$sample_type <- stringr::str_to_title(coldata_all$sample_type)
coldata_all$sample_type[coldata_all$sample_type == "Pdx"] <- "PDX"

df_ridge <- select(coldata_all, id, `% mito` = pct_counts_mito, `# genes detected` = total_features_by_counts, total_counts) %>% 
  mutate(`log10(# UMI)` = log10(total_counts)) %>% 
  select(-total_counts) %>% 
  gather(measure, value, -id)

ggplot(df_ridge, aes(x = value, y = id, group = id)) +
  geom_density_ridges(scale = 4, size = 0.25, alpha = 0.7) +
  facet_grid(~ measure, scales = "free_x") +
  labs(y = "Experiment") +
  # ggsci::scale_fill_npg(name = "Sample type") +
  theme_ridges(grid = FALSE, font_size = 10, center_axis_labels = TRUE) +
  theme(axis.text.y = element_blank(),
        axis.text.x = element_text(size = 8),
        legend.position = "top") +
  theme(axis.title.x = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white", colour = "white"))

ridge_plot <- last_plot()

```





## Check box

```{r}
df_grid <- select(coldata_all, id, sample_type, cancer_type, digestion_temperature, tissue_state, cell_status)
df_grid <- gather(df_grid, pheno, value, -id) %>% 
  distinct()

df_grid <- mutate(df_grid,
       pheno_new = case_when(
         pheno == "cancer_type" ~ "Cancer\ntype",
         pheno == "sample_type" ~ "Substrate",
         pheno == "digestion_temperature" ~ "Digestion\ntemperature",
         pheno == "tissue_state" ~ "Tissue\nstate",
         pheno == "cell_status" ~ "Cell\nstatus"
       ))

df_grid$pheno_new <- factor(
  df_grid$pheno_new,
  levels = c("Cell\nstatus", "Substrate", "Cancer\ntype", "Digestion\ntemperature", "Tissue\nstate" )
)

df_grid$value <- stringr::str_to_title(df_grid$value)
df_grid$value <- gsub("_", "\n", df_grid$value)
df_grid$value[df_grid$value == "Pdx"] <- "PDX"
df_grid$value[df_grid$value == "Digested\nfresh" | df_grid$value == "None"] <- "Fresh"

ggplot(df_grid, aes(x = value, y = id, fill = pheno_new)) +
  geom_point(size = 2, shape = 21, colour = 'grey20') +
  facet_grid(~ pheno_new, scales = "free_x", space = "free_x") +
  scale_fill_brewer(palette = "Spectral", guide = F) +
  labs(y = "Dark2") +
  theme_bw() +
  theme(axis.title = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        strip.text = element_text(face = "bold"),
        strip.background = element_rect(fill = "white", colour = "white"),
        axis.text.x = element_text(angle = -90, hjust = 0, vjust = 0.5))

grid_plot <- last_plot()
```

```{r}
cowplot::plot_grid(grid_plot, ridge_plot, 
                   nrow = 1, axis = 't', align = 'hv',
                   labels = c("B", "C"))

# ggsave("../../figs/all_sample_analyses/all_sample_overview-noumap.png", width = 10, height = 8)
```

```{r}

saveRDS(list('grid_plot'=grid_plot, 'ridge_plot'=ridge_plot), "../../figs/all_sample_analyses/rds_for_allen.rds")

source("fix_plot_allen.R")

umap_plot <- readRDS(params$input_umap_rds)

upper_grid <- make_upper_grid(grid_plot, ridge_plot)



full_plot <- cowplot::plot_grid(upper_grid,
                   cowplot::plot_grid(umap_plot, NULL, rel_widths = c(1, 0.02)),
                   rel_heights = c(2,1.2),
                   nrow = 2, #axis = 't', align = 'hv',
                   labels = c("", "D"))

ggsave(params$output_figure, plot = full_plot, width = 10, height = 8.5)
```


Final stats:

```{r}
ncells <- print(nrow(coldata_all))

print(glue::glue("We profiled {ncells} cells"))
```


