
base_path = "../../data/raw_10X"

experiments = {
    "10X_nuclei_900": "mm10",
    "10X_pbmc_4k": "GRCh38",
    "10X_t_3k": "GRCh38"
}

files_10X = ["barcodes.tsv", "genes.tsv", "matrix.mtx"]

file_dict = { k: expand(base_path + "/" + k + "/filtered_gene_bc_matrices/" + v + "/{file}", file = files_10X) for (k,v) in experiments.items() }

image_rds = expand("../../figs/comparison_to_10X_mito/{exp}.rds", exp = experiments.keys())

fig = "../../figs/comparison_to_10X_mito/comparison_to_10X_mito.png"

rule all:
    input:
        fig


rule analyze:
    input:
        f10X = lambda wildcards: file_dict[wildcards.exp]
    output:
        rds = "../../figs/comparison_to_10X_mito/{exp}.rds",
        html = "analyze_{exp}.html"
    shell:
        "Rscript -e \"rmarkdown::render('analyze_{wildcards.exp}.Rmd', \
        params = list(output_file = '{output.rds}'))\" "

rule fig:
    input:
        image_rds
    output:
        fig
    shell:
        "Rscript comparison_figure.R"

        
        







