---
title: "Bayesian core geneset construction"
output:
  html_document:
    df_print: paged
params:
  cellranger_version: v3
---

```{r}
suppressPackageStartupMessages({
  library(rstan)
  library(tidyverse)
  library(glue)
  library(GSEABase)
})

select <- dplyr::select
filter <- dplyr::filter
arrange <- dplyr::arrange
```

```{r}
mapping = c(
  "1"="SA854 (MDA-MB-231 TNBC cell line)",
  "2"="SA604X9XB2413 (TNBC PDX)",
  "3"="SA604X9XB2417 (TNBC PDX, prev. treated)",
  "4"="SA604X8XB02164 (TNBC PDX)",
  "5" ="SA604X7XB02089 (TNBC PDX)",
  "6"="SA604X6XB01979 (TNBC PDX)",
  "7"="PBC04106 (Breast patient sample)",
  "8"="VOA11267 (HGSC patient sample)",
  "9"="PBC04573 (Breast patient sample)",
  "10"="PBC04633 (Breast patient sample)",
  "11"="VOA11294C (HGSC patient sample)",
  "12"="VOA11294F (HGSC patient sample)",
  "13"="SA604X9XB2417 (TNBC PDX)",
  "14"="SA535X5XB02887 (TNBC PDX)"
)
```


```{r}
rds_files <- dir(glue("../../data/temp_de/{params$cellranger_version}"), full.names = TRUE, pattern="rds$")

df_de <- map_df(rds_files, readRDS)
```

```{r}
df_de$description <- plyr::mapvalues(df_de$comparison, from = names(mapping), to = mapping)

df_de <- filter(df_de, !grepl("patient", description))
```


```{r}
df_de <- count(df_de, ensembl_gene_id) %>% 
  dplyr::filter(n > 5) %>% 
  inner_join(df_de)
```


```{r}
model <- stan_model("coregene2.stan")
```

```{r}
logfcs <- select(df_de, gene_symbol, comparison, logFC) %>% 
  spread(gene_symbol, logFC) %>% 
  select(-comparison) %>% 
  as.matrix() %>% 
  t()

ses <- select(df_de, gene_symbol, comparison, se) %>% 
  spread(gene_symbol, se) %>% 
  select(-comparison) %>% 
  as.matrix() %>% 
  t()

logfcs[is.na(logfcs)] <- 10e5
ses[is.na(ses)] <- 10e5

is_missing <- 1 * (is.na(logfcs) & is.na(ses))

```

```{r}
data <- list(
  G = nrow(logfcs),
  E = ncol(logfcs),
  beta_obs = logfcs,
  beta_se = ses#,
  #is_missing = is_missing
)
```

```{r}
set.seed(1234L)
fit <- vb(model, data, grad_samples = 3)
```



```{r}
stan_hist(fit, 'phi')
```

```{r}
s <- summary(fit)
s <- s$summary

s <- s[grepl("^beta", rownames(s)),]
```

```{r}
dfc <- as_tibble(s) %>% 
  mutate(gene = rownames(logfcs)) %>% 
  select(gene, everything())

dfc <- dplyr::rename(dfc, lower = `2.5%`, upper = `97.5%`)
```

Add in core gene set genes

```{r}
dfc <- mutate(dfc, in_heat_geneset = lower > 0 | upper < 0)
```


```{r}
dfc_s <- filter(dfc, in_heat_geneset, abs(mean) > 0.5)

dfc_s <- arrange(dfc_s, desc(mean))

gene_order <- dfc_s$gene
dfc_s$gene <- factor(dfc_s$gene, levels = rev(gene_order))
```



```{r}
ggplot(dfc_s, aes(x = mean, y = gene)) +
  geom_errorbarh(aes(xmin = lower, xmax = upper), colour = 'grey50') +
  geom_point(aes(fill = mean), shape = 21, colour = 'black') +
  theme_bw(base_size = 10) +
  scale_fill_gradient2(low = scales::muted('blue'), high = scales::muted('red'), guide = FALSE) +
  labs(x = "Combined effect size (95% credible interval)", 
       y = "Gene", 
       subtitle = "Core heat response geneset with effect size > 0.5") 
```

Save the figure:

```{r}
saveRDS(
  last_plot(),
  glue("../../figs/temp_de/core_geneset-{params$cellranger_version}.rds")
)
```

Save core geneset results to RDS:

```{r}
heat_genes <- filter(dfc, in_heat_geneset) %>% .$gene

gs <- GeneSet(heat_genes, geneIdType = SymbolIdentifier(), setName = glue("scrnaseq-digestion-temperature-{params$cellranger_version}"))

toGmt(gs, glue("../../data/deliverables/scrnaseq-digestion-temperature-{params$cellranger_version}.gmt"))
```

And save the full data frame

```{r}
write_csv(dfc, glue("../../data/temp_de_all-{params$cellranger_version}.csv"))
```



